server:
  shutdown: graceful
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
spring:
  thymeleaf:
    mode: HTML
    cache: false

springdoc:
  api-docs:
    resolve-schema-properties: true
  swagger-ui:
    enabled: ${herodotus.switch.swagger.enabled}
    disable-swagger-default-url: true
    operations-sorter: method
    show-common-extensions: true
    show-extensions: true
    oauth:
      use-pkce-with-authorization-code-grant: true
      app-name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

feign:
  client:
    config:
      # 服务名，填写 default 为所有服务，或者指定某服务
      default:
        # 连接超时，10秒
        connectTimeout: 10000
        # 读取超时，20秒
        readTimeout: 20000
  httpclient:
    # 关闭 ApacheHttpClient
    enabled: false
    # 连接池连接最大连接数（缺省值 200）
    max-connections: 50
    # 连接最大闲置时间，单位为秒，600秒==10分钟（缺省值为 900秒==15分钟）
    time-to-live: 600
    # 开启压缩
  compression:
    request:
      enabled: true
    response:
      enabled: true
  okhttp:
    enabled: true
  sentinel:
    enabled: true
  hystrix:
    enabled: false

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 2000
  MaxAutoRetries: 1
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  http:
    client:
      enabled: false
  okhttp:
    enabled: true
  eager-load:
    enabled: true
  nacos:
    enabled: false

herodotus:
  rest:
    scan:
      enabled: ${herodotus.switch.rest.scan.enabled}